### ISSUE TITLE
Support for application parameters in fixtures

### ISSUE THREAD

**Issue by dvc** [khepin/KhepinYamlFixturesBundle#34]
for example:

```
# app/config/parameters.yml
parameters:
   base_path: web/files

#.../DataFixtures/data.yml
model: Me\MyBundle\Entity\File
fixtures:
  file1:
    src: %base_path%/1.jpg

SELECT * from File
id, src
1, web/files/1.jpg
```

It could helps for deploy and testing.
