### ISSUE TITLE
foreign key name lost after a service call

### ISSUE THREAD

**Issue by NinjDS** [khepin/KhepinYamlFixturesBundle#47]
Hi,

When using service call to persist data (FOSUser entities), the name of each fixture, which is used in relations on other entities, seems to be lost.

Example:

The CompanyUserBundle extends FOS User, so does the entity.

```
model: Company\UserBundle\Entity\User
persistence: orm
service_calls:
    service_1:
        service: fos_user.user_manager
        method: updateUser
fixtures:
    admin:
        firstname: Kevin
        lastname: John
        username: admin
        plain_password: passssssss
        email: me@example.com
        enabled: 1
        locked: 0
        expired: 0
        roles: []
```

Now, i'm supposed to use "admin" as reference in entities in relation with the users:

```
model: Company\MediaBundle\Entity\Tag
persistence: orm
fixtures:
    tag_1:
        name: "picture"
        description: "Just pictures"
        create_user: admin
```

But the "admin" key is not converted into the corresponding user by the loader. Instead, it gives setCreateUser() the string "admin". So i obvisously get this Exception in return:

> Catchable Fatal Error: Argument 1 passed to Company\MediaBundle\Entity\Tag::setCreateUser() must be an instance of Company\UserBundle\Entity\User, string given, called in ..........\vendor\khepin\yaml-fixtures-bundle\Khepin\YamlFixturesBundle\Fixture\OrmYamlFixture.php on line 40

Is there a way to use references even after a service call? Thank you guys.
