### ISSUE TITLE
Not working on Symfony 3.4 or Symfony 4 due the lack of Bundle

### ISSUE THREAD

**Issue by DavidGarciaCat** [khepin/KhepinYamlFixturesBundle#68]
Hello,

With a very simple configuration file...

```yaml
khepin_yaml_fixtures:
    directory: Resources/fixtures
    resources:
        - App
```

...it works free of errors on Symfony 2.8, however if I upgrade to Symfony 3.4 (clean install) or Symfony 4, then the code is not working with error message:

```
Bundle "App" does not exist or it is not enabled.
Maybe you forgot to add it in the registerBundles() method of your App\Kernel.php file?
```

Given new Symfony versions are working without bundles, I am unable to run the commands to include my fixtures on `dev` environment.

Some help might be appreciated.

Best,
